# 📊 **ANALISIS RETANBILDAD DE CRIPTOMONEDAS EN 2025**

**Autor:** Raúl Marcos Sánchez 

**Fecha:** 8 Mayo 2026

---

In [14]:
import pandas as pd
import numpy as np
#from sklearn.preprocessing import MinMaxScaler
from datetime import datetime

Cargamos los datos de metadata y los analizamos

In [15]:
df = pd.read_csv("../DATA/top_500_metadata.csv")
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,90034.0,1796670281875,1,1796670281875,3.439365e+10,91673.0,...,1.995901e+07,2.100000e+07,126080.0,-28.76949,2025-10-06T18:57:42.558Z,67.81,1.323416e+05,2013-07-06T00:00:00.000Z,NaN,2025-12-07T23:33:52.059Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,3047.62,367795025205,2,367795025205,2.098058e+10,3145.89,...,1.206954e+08,NaN,4946.05,-38.61498,2025-08-24T19:21:03.333Z,0.432979,7.011197e+05,2015-10-20T00:00:00.000Z,"{'times': 44.269447818807166, 'currency': 'btc...",2025-12-07T23:33:44.339Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.0,185668585289,3,191151709402,6.051337e+10,1.0,...,1.911141e+11,NaN,1.32,-24.40307,2018-07-24T00:00:00.000Z,0.572521,7.470440e+01,2015-03-02T00:00:00.000Z,NaN,2025-12-07T23:33:51.038Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,2.04,122855830675,4,203605167599,2.795817e+09,2.11,...,9.998575e+10,1.000000e+11,3.65,-44.26337,2025-07-18T03:40:53.808Z,0.00268621,7.555941e+04,2014-05-22T00:00:00.000Z,NaN,2025-12-07T23:33:49.957Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,892.15,122843693665,5,122843693665,1.401530e+09,905.07,...,1.377359e+08,2.000000e+08,1369.99,-35.04920,2025-10-13T08:41:24.131Z,0.0398177,2.234636e+06,2017-10-19T00:00:00.000Z,NaN,2025-12-07T23:33:51.812Z

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                500 non-null    str
 1   symbol                            500 non-null    str
 2   name                              500 non-null    str
 3   image                             500 non-null    str
 4   current_price                     500 non-null    str
 5   market_cap                        500 non-null    int64
 6   market_cap_rank                   500 non-null    int64
 7   fully_diluted_valuation           500 non-null    int64
 8   total_volume                      500 non-null    float64
 9   high_24h                          494 non-null    str
 10  low_24h                           494 non-null    str
 11  price_change_24h                  494 non-null    str
 12  price_change_percentage_24h       494 non-null    float64
 13  market_cap_change_24h             494 non-null    float64
 14  market_cap_change_percentage_24h  494 non-null    float64
 15  circulating_supply                500 non-null    float64
 16  total_supply                      500 non-null    float64
 17  max_supply                        254 non-null    float64
 18  ath                               500 non-null    str
 19  ath_change_percentage             500 non-null    float64
 20  ath_date                          500 non-null    str
 21  atl                               500 non-null    str
 22  atl_change_percentage             500 non-null    float64
 23  atl_date                          500 non-null    str
 24  roi                               41 non-null     str
 25  last_updated                      500 non-null    str
dtypes: float64(9), int64(3), str(14)
memory usage: 101.7 KB

In [17]:
df.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='str')

In [18]:
# Extraemos de la tabla original las columnas que nos sirven para la resolucion del ejercicio
metadata = df[["symbol","market_cap", "total_volume","ath","current_price","high_24h","low_24h" ]]
metadata

,symbol,market_cap,total_volume,ath,current_price,high_24h,low_24h
0,btc,1796670281875,3.439365e+10,126080.0,90034.0,91673.0,87887.0
1,eth,367795025205,2.098058e+10,4946.05,3047.62,3145.89,2941.77
2,usdt,185668585289,6.051337e+10,1.32,1.0,1.0,1.0
3,xrp,122855830675,2.795817e+09,3.65,2.04,2.11,2.0
4,bnb,122843693665,1.401530e+09,1369.99,892.15,905.07,871.83
...,...,...,...,...,...,...,...
495,bc,77362507,1.798137e+04,0.01100698,0.00775978,0.00807202,0.00761125
496,vrsc,77313716,4.921460e+03,6.74,0.970701,0.980527,0.945662
497,vkhype,77308785,7.712420e+05,51.63,29.68,31.61,28.59
498,cfg,76741291,1.007799e+06,0.400363,0.133882,0.13742,0.127505
499,wmtx,76588104,1.036002e+07,0.979732,0.095677,0.098904,0.094648

In [19]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   symbol         500 non-null    str
 1   market_cap     500 non-null    int64
 2   total_volume   500 non-null    float64
 3   ath            500 non-null    str
 4   current_price  500 non-null    str
 5   high_24h       494 non-null    str
 6   low_24h        494 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 27.5 KB

Limpieza basica de los datos que contienen las columnas con las que vamos a trabajar.

Convertimos columnas las columnas str a columnas numericas

In [20]:
cols_numeric = ["market_cap", "total_volume","ath","current_price","high_24h","low_24h"]
for col in cols_numeric:
    metadata[col] = pd.to_numeric(metadata[col], errors="coerce")

# Eliminar filas con datos faltantes en métricas clave
metadata = metadata.dropna(subset=cols_numeric)

# Cálculamos las métricas necesarias.

Volatilidad 24H

In [21]:
#volatilidad 24H
metadata["volatility_24h"] = (metadata["high_24h"] - metadata["low_24h"]) / metadata["current_price"]

Distancia al ATH

In [22]:
#distancia al ATH
metadata["ath_distance"] = (metadata["ath"] - metadata["current_price"]) / metadata["ath"]

In [23]:
metadata

,symbol,market_cap,total_volume,ath,current_price,high_24h,low_24h,volatility_24h,ath_distance
0,btc,1796670281875,3.439365e+10,126080.000000,90034.000000,91673.000000,87887.000000,0.042051,0.285898
1,eth,367795025205,2.098058e+10,4946.050000,3047.620000,3145.890000,2941.770000,0.066977,0.383827
2,usdt,185668585289,6.051337e+10,1.320000,1.000000,1.000000,1.000000,0.000000,0.242424
3,xrp,122855830675,2.795817e+09,3.650000,2.040000,2.110000,2.000000,0.053922,0.441096
4,bnb,122843693665,1.401530e+09,1369.990000,892.150000,905.070000,871.830000,0.037258,0.348791
...,...,...,...,...,...,...,...,...,...
495,bc,77362507,1.798137e+04,0.011007,0.007760,0.008072,0.007611,0.059379,0.295013
496,vrsc,77313716,4.921460e+03,6.740000,0.970701,0.980527,0.945662,0.035917,0.855979
497,vkhype,77308785,7.712420e+05,51.630000,29.680000,31.610000,28.590000,0.101752,0.425140
498,cfg,76741291,1.007799e+06,0.400363,0.133882,0.137420,0.127505,0.074058,0.665598
499,wmtx,76588104,1.036002e+07,0.979732,0.095677,0.098904,0.094648,0.044483,0.902344

In [24]:
metadata.columns

Index(['symbol', 'market_cap', 'total_volume', 'ath', 'current_price',
       'high_24h', 'low_24h', 'volatility_24h', 'ath_distance'],
      dtype='str')

🏆 5. Ranking multicriterio. Ponderamos los datos en funcion de su importancia para el analisis a realizar.


Market Cap → 40%

Volumen → 30%

Volatilidad → 20%

Distancia al ATH → 10%

In [25]:
metadata["ranking"] = (0.40 * metadata["market_cap"] + 0.30 * metadata["total_volume"] + 0.20 * metadata["volatility_24h"] + 0.10 * metadata["ath_distance"])

# 🥇 6. Selección de los 5 criptoactivos más importantes

In [26]:
top5 = metadata.sort_values("ranking", ascending=False).head(5)
top5_assets = top5["symbol"].tolist()

print("Los 5 criptoactivos seleccionados son:")
print(top5_assets)

top5

Los 5 criptoactivos seleccionados son:
['btc', 'eth', 'usdt', 'xrp', 'bnb']

,symbol,market_cap,total_volume,ath,current_price,high_24h,low_24h,volatility_24h,ath_distance,ranking
0,btc,1796670281875,3.439365e+10,126080.00,90034.00,91673.00,87887.00,0.042051,0.285898,7.289862e+11
1,eth,367795025205,2.098058e+10,4946.05,3047.62,3145.89,2941.77,0.066977,0.383827,1.534122e+11
2,usdt,185668585289,6.051337e+10,1.32,1.00,1.00,1.00,0.000000,0.242424,9.242145e+10
3,xrp,122855830675,2.795817e+09,3.65,2.04,2.11,2.00,0.053922,0.441096,4.998108e+10
4,bnb,122843693665,1.401530e+09,1369.99,892.15,905.07,871.83,0.037258,0.348791,4.955794e+10

# 📈 7. Preparar datos OHLC para el PASO 2

In [27]:
ohlc = pd.read_csv("../DATA/crypto_ohlc.csv")
ohlc.head()

,coin_id,symbol,timestamp,date,open,high,low,close
0,bitcoin,btc,1733529600000,2024-12-07,97072.0,102034.0,96589.0,99974.0
1,bitcoin,btc,1733875200000,2024-12-11,99928.0,101235.0,94387.0,96650.0
2,bitcoin,btc,1734220800000,2024-12-15,96643.0,102658.0,95741.0,101367.0
3,bitcoin,btc,1734566400000,2024-12-19,101393.0,108135.0,100237.0,100356.0
4,bitcoin,btc,1734912000000,2024-12-23,100139.0,102759.0,92245.0,95094.0

In [28]:
ohlc.info()

<class 'pandas.DataFrame'>
RangeIndex: 39235 entries, 0 to 39234
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   coin_id    39235 non-null  str
 1   symbol     39235 non-null  str
 2   timestamp  39235 non-null  int64
 3   date       39235 non-null  str
 4   open       39235 non-null  str
 5   high       39235 non-null  str
 6   low        39235 non-null  str
 7   close      39235 non-null  str
dtypes: int64(1), str(7)
memory usage: 2.4 MB

In [29]:
cols_numeric = ["open", "high","low","close"]
for col in cols_numeric:
    ohlc[col] = pd.to_numeric(ohlc[col], errors="coerce")

# Eliminar filas con datos faltantes en métricas clave
ohlc = ohlc.dropna(subset=cols_numeric)

In [30]:
ohlc.info()

<class 'pandas.DataFrame'>
Index: 38625 entries, 0 to 39234
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   coin_id    38625 non-null  str
 1   symbol     38625 non-null  str
 2   timestamp  38625 non-null  int64
 3   date       38625 non-null  str
 4   open       38625 non-null  float64
 5   high       38625 non-null  float64
 6   low        38625 non-null  float64
 7   close      38625 non-null  float64
dtypes: float64(4), int64(1), str(3)
memory usage: 2.7 MB

Transformar la columna fecha

In [31]:
ohlc.columns

Index(['coin_id', 'symbol', 'timestamp', 'date', 'open', 'high', 'low',
       'close'],
      dtype='str')

In [32]:
# Filtrar solo los 5 activos seleccionados
ohlc_top5 = ohlc[ohlc["symbol"].isin(top5_assets)]
ohlc_top5

,coin_id,symbol,timestamp,date,open,high,low,close
0,bitcoin,btc,1733529600000,2024-12-07,97072.000000,102034.0,96589.000000,99974.000000
1,bitcoin,btc,1733875200000,2024-12-11,99928.000000,101235.0,94387.000000,96650.000000
2,bitcoin,btc,1734220800000,2024-12-15,96643.000000,102658.0,95741.000000,101367.000000
3,bitcoin,btc,1734566400000,2024-12-19,101393.000000,108135.0,100237.000000,100356.000000
4,bitcoin,btc,1734912000000,2024-12-23,100139.000000,102759.0,92245.000000,95094.000000
...,...,...,...,...,...,...,...,...
36924,cronos-bridged-usdt-cronos,usdt,1763596800000,2025-11-20,1001.000000,1009.0,0.989211,1.000000
36925,cronos-bridged-usdt-cronos,usdt,1763942400000,2025-11-24,1.000000,1008.0,0.992097,0.998818
36926,cronos-bridged-usdt-cronos,usdt,1764288000000,2025-11-28,0.999405,1006.0,0.994320,0.998501
36927,cronos-bridged-usdt-cronos,usdt,1764633600000,2025-12-02,0.998805,1006.0,0.986816,0.997944
36928,cronos-bridged-usdt-cronos,usdt,1764979200000,2025-12-06,0.998712,1011.0,0.990898,0.999585

In [33]:
ohlc_top5.columns

Index(['coin_id', 'symbol', 'timestamp', 'date', 'open', 'high', 'low',
       'close'],
      dtype='str')

# 🧪 8. Cálculo de rentabilidad 2025 (para hipótesis)

transformamos la columna fecha a tipo de caracter date

In [34]:
from datetime import datetime

In [35]:
# Convertir timestamp
#ohlc_top5['timestamp'] = ohlc_top5['timestamp'].astype(float)
ohlc_top5['date'] = pd.to_datetime(ohlc_top5['timestamp'], unit='ms')

In [37]:
ohlc_top5.info()

<class 'pandas.DataFrame'>
Index: 644 entries, 0 to 36928
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   coin_id    644 non-null    str
 1   symbol     644 non-null    str
 2   timestamp  644 non-null    int64
 3   date       644 non-null    datetime64[ms]
 4   open       644 non-null    float64
 5   high       644 non-null    float64
 6   low        644 non-null    float64
 7   close      644 non-null    float64
dtypes: datetime64[ms](1), float64(4), int64(1), str(2)
memory usage: 45.3 KB

In [36]:
# Convertir fecha
ohlc_top5["date"] = pd.to_datetime(ohlc_top5["date"], unit='ms')

# Filtrar año 2025
ohlc_2025 = ohlc_top5[
    (ohlc_top5["date"] >= "2025-01-01") &
    (ohlc_top5["date"] <= "2025-12-31")
]

# Rentabilidad anual por activo
returns_2025 = (
    ohlc_2025.groupby("symbol")
    .apply(lambda df: (df["close"].iloc[-1] - df["close"].iloc[0]) / df["close"].iloc[0])
    .reset_index(name="annual_return")
)

returns_2025

  symbol  annual_return
0    bnb       0.239282
1    btc      -0.089485
2    eth      -0.161372
3   usdt       0.000085
4    xrp      -0.167347