# 📊 **ANALISIS RETANBILDAD DE CRIPTOMONEDAS EN 2025**

**Autor:** Raúl Marcos Sánchez 

**Fecha:** 8 Mayo 2026

---

In [30]:
import pandas as pd
import numpy as np

cargamos los datos y los analizamos

In [31]:
df = pd.read_csv("../DATA/top_500_metadata.csv")
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,90034.0,1796670281875,1,1796670281875,3.439365e+10,91673.0,...,1.995901e+07,2.100000e+07,126080.0,-28.76949,2025-10-06T18:57:42.558Z,67.81,1.323416e+05,2013-07-06T00:00:00.000Z,NaN,2025-12-07T23:33:52.059Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,3047.62,367795025205,2,367795025205,2.098058e+10,3145.89,...,1.206954e+08,NaN,4946.05,-38.61498,2025-08-24T19:21:03.333Z,0.432979,7.011197e+05,2015-10-20T00:00:00.000Z,"{'times': 44.269447818807166, 'currency': 'btc...",2025-12-07T23:33:44.339Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.0,185668585289,3,191151709402,6.051337e+10,1.0,...,1.911141e+11,NaN,1.32,-24.40307,2018-07-24T00:00:00.000Z,0.572521,7.470440e+01,2015-03-02T00:00:00.000Z,NaN,2025-12-07T23:33:51.038Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,2.04,122855830675,4,203605167599,2.795817e+09,2.11,...,9.998575e+10,1.000000e+11,3.65,-44.26337,2025-07-18T03:40:53.808Z,0.00268621,7.555941e+04,2014-05-22T00:00:00.000Z,NaN,2025-12-07T23:33:49.957Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,892.15,122843693665,5,122843693665,1.401530e+09,905.07,...,1.377359e+08,2.000000e+08,1369.99,-35.04920,2025-10-13T08:41:24.131Z,0.0398177,2.234636e+06,2017-10-19T00:00:00.000Z,NaN,2025-12-07T23:33:51.812Z

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                500 non-null    str
 1   symbol                            500 non-null    str
 2   name                              500 non-null    str
 3   image                             500 non-null    str
 4   current_price                     500 non-null    str
 5   market_cap                        500 non-null    int64
 6   market_cap_rank                   500 non-null    int64
 7   fully_diluted_valuation           500 non-null    int64
 8   total_volume                      500 non-null    float64
 9   high_24h                          494 non-null    str
 10  low_24h                           494 non-null    str
 11  price_change_24h                  494 non-null    str
 12  price_change_percentage_24h       494 non-null    float64
 13  market_cap_change_24h             494 non-null    float64
 14  market_cap_change_percentage_24h  494 non-null    float64
 15  circulating_supply                500 non-null    float64
 16  total_supply                      500 non-null    float64
 17  max_supply                        254 non-null    float64
 18  ath                               500 non-null    str
 19  ath_change_percentage             500 non-null    float64
 20  ath_date                          500 non-null    str
 21  atl                               500 non-null    str
 22  atl_change_percentage             500 non-null    float64
 23  atl_date                          500 non-null    str
 24  roi                               41 non-null     str
 25  last_updated                      500 non-null    str
dtypes: float64(9), int64(3), str(14)
memory usage: 101.7 KB

top_500_metadata.csv
Contiene datos de instantáneas de las 500 monedas más populares.

id: Identificador único de CoinGecko (por ejemplo, bitcoin, solana).
symbol: Símbolo bursátil (por ejemplo, btc, sol).
name: Nombre completo del activo.
image: URL del logo de la moneda.
current_price: Último precio de mercado en USD.
market_cap: Capitalización bursátil total en USD.
market_cap_rank: Clasificación global por capitalización bursátil.
fully_diluted_valuation: Capitalización de mercado teórica si la máxima oferta estuviera en circulación.
total_volume: Volumen de negociación las 24 horas.
high_24h / low_24h: Precio más alto y más bajo en las últimas 24 horas.
price_change_24h: Cambio absoluto de precio en las últimas 24 horas.
price_change_percentage_24h: Porcentaje de cambio en el precio en las últimas 24 horas.
circulating_supply: Cantidad de monedas actualmente en el mercado.
total_supply: Cantidad total de monedas creadas.
max_supply: Cantidad máxima de monedas que existirá jamás.
ath: Precio máximo histórico.
atl: Precio más bajo de todos los tiempos.
last_updated: Marca temporal de la instantánea de metadatos.

In [33]:
# Obtener los nombres de las columnas como lista
nombres_columnas = df.columns.tolist()
print(nombres_columnas)

['id', 'symbol', 'name', 'image', 'current_price', 'market_cap', 'market_cap_rank', 'fully_diluted_valuation', 'total_volume', 'high_24h', 'low_24h', 'price_change_24h', 'price_change_percentage_24h', 'market_cap_change_24h', 'market_cap_change_percentage_24h', 'circulating_supply', 'total_supply', 'max_supply', 'ath', 'ath_change_percentage', 'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi', 'last_updated']

visto que tenemos columnas que nos aportan informacion que no vamos a usar vamos hacer una limpieza de la tabla, para quedarmos unicamente con las columnas

In [34]:
# Extraemos de la tabla original las columnas que nos sirven para la resolucion del ejercicio
df_operativo = df[["symbol","last_updated", "current_price","market_cap","high_24h","low_24h", ]].set_index(["symbol"])
df_operativo

,last_updated,current_price,market_cap,high_24h,low_24h
symbol,,,,,
btc,2025-12-07T23:33:52.059Z,90034.0,1796670281875,91673.0,87887.0
eth,2025-12-07T23:33:44.339Z,3047.62,367795025205,3145.89,2941.77
usdt,2025-12-07T23:33:51.038Z,1.0,185668585289,1.0,1.0
xrp,2025-12-07T23:33:49.957Z,2.04,122855830675,2.11,2.0
bnb,2025-12-07T23:33:51.812Z,892.15,122843693665,905.07,871.83
...,...,...,...,...,...
bc,2025-12-07T23:33:00.236Z,0.00775978,77362507,0.00807202,0.00761125
vrsc,2025-12-07T23:33:00.205Z,0.970701,77313716,0.980527,0.945662
vkhype,2025-12-07T23:33:00.193Z,29.68,77308785,31.61,28.59
cfg,2025-12-07T23:33:00.332Z,0.133882,76741291,0.13742,0.127505
wmtx,2025-12-07T23:33:00.292Z,0.095677,76588104,0.098904,0.094648

In [35]:
df_operativo.info()

<class 'pandas.DataFrame'>
Index: 500 entries, btc to wmtx
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   last_updated   500 non-null    str
 1   current_price  500 non-null    str
 2   market_cap     500 non-null    int64
 3   high_24h       494 non-null    str
 4   low_24h        494 non-null    str
dtypes: int64(1), str(4)
memory usage: 23.4+ KB