# 📊 **ANALISIS RETANBILDAD DE CRIPTOMONEDAS EN 2025**

**Autor:** Raúl Marcos Sánchez 

**Fecha:** 8 Mayo 2026

---

## 🌟 Descripción del Proyecto
Este proyecto presenta un análisis exploratorio de datos (EDA) la rentabilidad de las 10 criptomonedas mas importates seleccionadas a tra ves de unos criterios establecidos como:
- **Comparación de Capitalización de mercado (Market Cap)**
- **Análisis de Volatilidad en 24 Horas**
- **Análisis de Volumen de Trading**
- **Análisis de Máximos Históricos (ATH)**

---

## 💡 Hipótesis del proyecto:

- **¿Qué Criptomoneda tuvo el valor de cotización más alto del año 2025?**
- **¿En qué mes se registraron las mayores caídas y en cual los mayores incrementos?**
- **¿Cuál ha sido la criptomoneda mas más rentable en este año? (utilizamos el ROI)**
- **Average change (Volatilidad de la inversión)**

---

## 📈💰📊 Datos iniciales:

In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../CODIGO/DATA/top_500_metadata.csv")
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,90034.0,1796670281875,1,1796670281875,3.439365e+10,91673.0,...,1.995901e+07,2.100000e+07,126080.0,-28.76949,2025-10-06T18:57:42.558Z,67.81,1.323416e+05,2013-07-06T00:00:00.000Z,NaN,2025-12-07T23:33:52.059Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,3047.62,367795025205,2,367795025205,2.098058e+10,3145.89,...,1.206954e+08,NaN,4946.05,-38.61498,2025-08-24T19:21:03.333Z,0.432979,7.011197e+05,2015-10-20T00:00:00.000Z,"{'times': 44.269447818807166, 'currency': 'btc...",2025-12-07T23:33:44.339Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.0,185668585289,3,191151709402,6.051337e+10,1.0,...,1.911141e+11,NaN,1.32,-24.40307,2018-07-24T00:00:00.000Z,0.572521,7.470440e+01,2015-03-02T00:00:00.000Z,NaN,2025-12-07T23:33:51.038Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,2.04,122855830675,4,203605167599,2.795817e+09,2.11,...,9.998575e+10,1.000000e+11,3.65,-44.26337,2025-07-18T03:40:53.808Z,0.00268621,7.555941e+04,2014-05-22T00:00:00.000Z,NaN,2025-12-07T23:33:49.957Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,892.15,122843693665,5,122843693665,1.401530e+09,905.07,...,1.377359e+08,2.000000e+08,1369.99,-35.04920,2025-10-13T08:41:24.131Z,0.0398177,2.234636e+06,2017-10-19T00:00:00.000Z,NaN,2025-12-07T23:33:51.812Z

---

## 📈💰📊 Definicion de las columnas:

**top_500_metadata.csv:** Contiene datos de las 500 monedas más populares.

-**id:** Identificador único de CoinGecko (por ejemplo, bitcoin, solana).

-**symbol:** Símbolo bursátil (por ejemplo, btc, sol).

-**name:** Nombre completo del activo.

-**image:** URL del logo de la moneda.

-**current_price:** Último precio de mercado en USD.

-**market_cap:** Capitalización bursátil total en USD.

-**market_cap_rank:** Clasificación global por capitalización bursátil.

-**fully_diluted_valuation:** Capitalización de mercado teórica si la máxima oferta estuviera en circulación.

-**total_volume:** Volumen de negociación las 24 horas.

-**high_24h / low_24h:** Precio más alto y más bajo en las últimas 24 horas.

-**price_change_24h:** Cambio absoluto de precio en las últimas 24 horas.

-**price_change_percentage_24h:** Porcentaje de cambio en el precio en las últimas 24 horas.

-**circulating_supply:** Cantidad de monedas actualmente en el mercado.

-**total_supply:** Cantidad total de monedas creadas.

-**max_supply:** Cantidad máxima de monedas que existirá jamás.

-**ath:** Precio máximo histórico.

-**atl:** Precio más bajo de todos los tiempos.

-**last_updated:** Marca temporal de la instantánea de metadatos.

---

In [4]:
df = pd.read_csv("../CODIGO/DATA/crypto_ohlc.csv")
df.head()

,coin_id,symbol,timestamp,date,open,high,low,close
0,bitcoin,btc,1733529600000,2024-12-07,97072.0,102034.0,96589.0,99974.0
1,bitcoin,btc,1733875200000,2024-12-11,99928.0,101235.0,94387.0,96650.0
2,bitcoin,btc,1734220800000,2024-12-15,96643.0,102658.0,95741.0,101367.0
3,bitcoin,btc,1734566400000,2024-12-19,101393.0,108135.0,100237.0,100356.0
4,bitcoin,btc,1734912000000,2024-12-23,100139.0,102759.0,92245.0,95094.0

**crypto_ohlc.csv:** Contiene datos de las monedas filtradas de las 500.

-**coin_id:** Identificador de la crypto

-**symbol:** Simbolo de la crypto

-**timestamp:**  registrar automáticamente la fecha y hora de creación o modificación de un registro

-**data:** Fecha del registro de los valores

-**open:** Valor de la crypto registrado en la apertura de mercado

-**high:** Valor mas alto registrado en la fecha definida

-**low:** Valor mas bajo registrado en la fecha definida

-**close:** Valor de cierre registrado en la fecha definida